<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 11/4/19
 * Time: 2:11 PM
 */

namespace App\Repository;

use App\Entity\Block;
use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    /**
     * @param Block $block
     * @return array|null
     */
    public function getBlockConfirmations(Block $block)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b) as confirmationsCount')
            ->where('b.id > :id')
            ->setParameter('id', $block->getId())
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Block $block
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getPreviousBlock(Block $block)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.id < :id')
            ->setParameter('id', $block->getId())
            ->orderBy('b.id', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param Block|null $block
     * @param int $count
     * @return array|null
     */
    public function getBlocks(Block $block = null, $count = 10)
    {
        if ($block) {
            return $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.signTime < :signTime')
                ->setParameter('signTime', $block->getSignTime())
                ->setMaxResults($count)
                ->orderBy('b.signTime', 'desc')
                ->getQuery()
                ->getResult();
        } else {
            return $this->createQueryBuilder('b')
                ->select('b')
                ->setMaxResults($count)
                ->orderBy('b.signTime', 'desc')
                ->getQuery()
                ->getResult();
        }
    }

    /**
     * @param int $year
     * @param int $month
     * @param int $day
     * @param Block|null $block
     * @param int $count
     * @return array|null
     */
    public function getBlocksByDate(int $year, int $month, int $day, Block $block = null, int $count = 10)
    {
        $timezoneObj = new \DateTimeZone('UTC');
        $dateObj = new \DateTime();
        $dateObj->setDate($year, $month, $day);
        $dateObj->setTime(0, 0);
        $dateObj->setTimezone($timezoneObj);

        if ($block) {
            return $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.signTime >= :fromDate')
                ->andWhere('b.signTime < :toDate')
                ->setParameters(['fromDate' => $dateObj->getTimestamp(), 'toDate' => $block->getSignTime()])
                ->setMaxResults($count)
                ->orderBy('b.signTime', 'desc')
                ->getQuery()
                ->getResult();
        } else {
            return $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.signTime >= :fromDate')
                ->andWhere('b.signTime < :toDate')
                ->setParameters(['fromDate' => $dateObj->getTimestamp(), 'toDate' => $dateObj->getTimestamp() + 86400])
                ->setMaxResults($count)
                ->orderBy('b.signTime', 'desc')
                ->getQuery()
                ->getResult();
        }
    }

    /**
     * @param string $identifier
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findBlock(string $identifier)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.hash = :identifier')
            ->orWhere('b.number = :identifier')
            ->setParameter('identifier', $identifier)
            ->orderBy('b.id', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}