<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 1/30/19
 * Time: 1:59 PM
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    /**
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLastBlock()
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->orderBy('b.signTime', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}