<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 3/22/19
 * Time: 6:01 PM
 */

namespace App\Repository;

use App\Entity\Publication;
use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationMemberRepository extends EntityRepository
{
    public function getPublicationInvitations(Publication $publication)
    {
        return $this->createQueryBuilder('pm')
            ->select('pm, p')
            ->join('pm.publication', 'p')
            ->where('p = :publication')
            ->andWhere('pm.status > 100')
            ->andWhere('pm.status < 200')
            ->setParameter('publication', $publication)
            ->getQuery()
            ->getResult();
    }

    public function getPublicationRequests(Publication $publication)
    {
        return $this->createQueryBuilder('pm')
            ->select('pm, p')
            ->join('pm.publication', 'p')
            ->where('pm.publication = :publication')
            ->andWhere('pm.status > 200')
            ->setParameter('publication', $publication)
            ->getQuery()
            ->getResult();
    }
}