<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 11/4/19
 * Time: 2:18 PM
 */

namespace App\Repository;

use App\Entity\Account;
use Doctrine\ORM\EntityRepository;
use PubliqAPI\Base\RewardType;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends EntityRepository
{
    /**
     * @param Account $account
     * @param string $rewardType
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAccountRewardSummary(Account $account, string $rewardType = null)
    {
        if ($rewardType) {
            return $this->createQueryBuilder('r')
                ->select('SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction')
                ->where('r.to = :user')
                ->andWhere('r.rewardType = :rewardType')
                ->setParameters(['user' => $account, 'rewardType' => $rewardType])
                ->getQuery()
                ->getOneOrNullResult();
        } else {
            return $this->createQueryBuilder('r')
                ->select('SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction')
                ->where('r.to = :user')
                ->setParameters(['user' => $account])
                ->getQuery()
                ->getOneOrNullResult();
        }
    }

    /**
     * @param string $rewardType
     * @param int $timestamp
     * @return array|null
     */
    public function getTopRewardsByType(string $rewardType, int $timestamp = 0)
    {
        if ($rewardType == 'all') {
            return $this->createQueryBuilder('r')
                ->select('a.publicKey, SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction, r.rewardType')
                ->join('r.to', 'a')
                ->join('r.block', 'b')
                ->where('b.signTime > :timestamp')
                ->andWhere('r.rewardType != :exception1')
                ->andWhere('r.rewardType != :exception2')
                ->setParameters(['timestamp' => $timestamp, 'exception1' => RewardType::initial, 'exception2' => RewardType::sponsored_return])
                ->groupBy('r.to')
                ->addGroupBy('r.to')
                ->addGroupBy('r.rewardType')
                ->addOrderBy('totalWhole', 'desc')
                ->addOrderBy('totalFraction', 'desc')
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        } else {
            return $this->createQueryBuilder('r')
                ->select('a.publicKey, SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction, r.rewardType')
                ->join('r.to', 'a')
                ->join('r.block', 'b')
                ->where('r.rewardType = :rewardType')
                ->andWhere('b.signTime > :timestamp')
                ->andWhere('r.rewardType != :exception1')
                ->andWhere('r.rewardType != :exception2')
                ->setParameters(['rewardType' => $rewardType, 'timestamp' => $timestamp, 'exception1' => RewardType::initial, 'exception2' => RewardType::sponsored_return])
                ->groupBy('r.to')
                ->addOrderBy('totalWhole', 'desc')
                ->addOrderBy('totalFraction', 'desc')
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        }
    }
}