<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 11/4/19
 * Time: 2:18 PM
 */

namespace App\Repository;

use App\Entity\Account;
use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends EntityRepository
{
    /**
     * @param Account $account
     * @param string $rewardType
     * @return array|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAccountRewardSummary(Account $account, string $rewardType = null)
    {
        if ($rewardType) {
            return $this->createQueryBuilder('r')
                ->select('SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction')
                ->where('r.to = :user')
                ->andWhere('r.rewardType = :rewardType')
                ->setParameters(['user' => $account, 'rewardType' => $rewardType])
                ->getQuery()
                ->getOneOrNullResult();
        } else {
            return $this->createQueryBuilder('r')
                ->select('SUM(r.whole) as totalWhole, SUM(r.fraction) as totalFraction')
                ->where('r.to = :user')
                ->setParameters(['user' => $account])
                ->getQuery()
                ->getOneOrNullResult();
        }
    }
}