<?php
/**
 * Created by PhpStorm.
 * User: Grigor
 * Date: 9/6/19
 * Time: 5:47 PM
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * @return array|null
     */
    public function getTagsByPopularity()
    {
        $subQuery = $this->getEntityManager()
            ->createQuery("
                select max(cu2)
                from App:Block bl
                join App:Transaction tr with bl = tr.block
                join App:ContentUnit cu2 with cu2 = tr.contentUnit
                group by cu2.contentId
            ");

        $query = $this->createQueryBuilder('t');

        return $query->select('t, (COUNT(cu) + COUNT(p)) as totalCount')
            ->leftJoin('t.contentUnits', 'cu')
            ->leftJoin('t.publications', 'p')
            ->where($query->expr()->in('cu.contentUnit', $subQuery->getDQL()))
            ->having('totalCount > 0')
            ->addOrderBy('totalCount', 'DESC')
            ->addOrderBy('t.name', 'ASC')
            ->groupBy('t.id')
            ->getQuery()
            ->getResult('AGGREGATES_HYDRATOR');
    }
}
